name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Ssh and deploy
      env: 
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh -t -i keyfile ec2-user@ec2-18-206-227-119.compute-1.amazonaws.com source ~/deploy.sh



